apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: chatonode/expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            # NATS
            - name: NATS_CLUSTER_ID
              value: zombilet
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # Pod Name
            - name: NATS_URL
              value: 'http://nats-streaming-srv:4222'

---
# Expiration deployment does not need a ClusterIP Service:
#   -> Since deployment itself is going to communicate with STAN asynchronously.
